### ISSUE TITLE
Background notifications not working

### ISSUE THREAD

**Issue by EddyVerbruggen** [codingsett/NativescriptTestNotification#1]
Moved from https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/1173

Question: where in your code are you triggering usage of push notifications? At the very least, either `onMessageReceivedCallback` or `onPushTokenReceivedCallback ` is needed during `init`, or `addOnMessageReceivedCallback` / `addOnPushTokenReceivedCallback` at any moment after running `init`.

**Comment by codingsett** [comment]
I was triggering it in app.js file but since it did not trigger notifications when the app is killed i used this code

```
firebase.init({
    showNotifications: true,
}).then(
    function () {
      console.log("firebase.init done");
    },
    function (error) {
      console.log("firebase.init error: " + error);
    }
);
```

**Comment by codingsett** [comment]
This was the code when i was using `onMessageReceivedCallback` in the firebase init function

```
onMessageReceivedCallback: function (message) {
        localnotify.schedule([{
            id: Math.floor((Math.random() * 100) + 1),
            title: message.title,
            body: message.body,
            ticker: 'The ticker',
            badge: 1,
            sound: "sound1" //sound1 from /Appresources/raw/ folder

        }]).then(
            function () {
                console.log("Notification scheduled 1");
            },
            function (error) {
                console.log("scheduling error: " + error);
            }
        );
```

**Comment by EddyVerbruggen** [comment]
Would you mind updating the repo so it's in the state where we can verify the issue with Firebase push  notifications properly configured, but not working in the background on Android?

**Comment by codingsett** [comment]
yeah sure

**Comment by codingsett** [comment]
Instead of dabbling with the demo app i provide you the real project in a private repo so that you can easily find the underlying issues(all configurations are correct) and thanks for taking your time to assist.
https://github.com/codingsett/FX_SIGNALS/issues/1

**Comment by EddyVerbruggen** [comment]
I can't access that repo.

**Comment by codingsett** [comment]
sent you an invite

**Comment by EddyVerbruggen** [comment]
Deployed. Do I need a login? And after logging in, is there anything else I need to do to reproduce your issue?

**Comment by codingsett** [comment]
yes after you login then you should start receiving alerts i can send some test notifications on firebase ...when you are ready tell me and will send the notifications so that you see what am talking about
username == primo 
password == 12345

**Comment by EddyVerbruggen** [comment]
OK, moving to https://github.com/codingsett/FX_SIGNALS/issues/1
